#196752 update user
tekdi/sunbird-admin-ui pull request #11
Opened 2023-05-23 09:27 UTC by snehalsabade

2023-05-25 09:55 UTC, gouravmore approved these changes

2023-05-29 04:24 UTC, gouravmore requested changes

2023-05-29 04:24 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-user/add-edit-user/add-edit-user.component.ts
> +        { severity: 'success', summary: 'Roles added successfully', detail: response.params.status }
language const should use here

2023-05-29 04:24 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-user/sbuser.component.ts
> +        this.messageService.add({ severity: 'success', summary: 'Success', detail: response.params.status })
use language constants

2023-05-29 04:39 UTC, snehalsabade commented on src/app/sb-admin/components/pages/sb-user/sbuser.component.ts
> +        this.messageService.add({ severity: 'success', summary: 'Success', detail: response.params.status })
removed summary

2023-05-29 04:39 UTC, snehalsabade commented on src/app/sb-admin/components/pages/sb-user/add-edit-user/add-edit-user.component.ts
> +        { severity: 'success', summary: 'Roles added successfully', detail: response.params.status }
Removed summary

2023-05-31 04:56 UTC, gouravmore approved these changes

2023-05-31 04:58 UTC, merged