Added Organization functionality
tekdi/sunbird-admin-ui pull request #12
Opened 2023-05-24 10:01 UTC by poojakarma

2023-05-25 07:23 UTC, gouravmore requested changes

2023-05-25 07:23 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/add-or-edit-org/add-or-edit-org.component.ts
> +      { name: 'school', value: 'school' },
why this is hardcoded here

2023-05-25 07:23 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/add-or-edit-org/add-or-edit-org.component.ts
> +        { severity: 'error', detail: 'Fields should not be blank' }
use language constants

2023-05-25 07:23 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/add-or-edit-org/add-or-edit-org.component.ts
> +      if (error.status = 400) {
are you assigning the 400 value to error.status?

2023-05-25 07:23 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/add-or-edit-org/add-or-edit-org.component.ts
> +          { severity: 'error', detail: 'Channel Already Exit' }
use language constants

2023-05-25 07:23 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +    this.ref = this.dialogService.open(AddOrEditOrgComponent, {
move this object in variable declaration section

2023-05-25 07:23 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +    this.messageService.add({ severity: 'success', summary: 'Success', detail: message });
what message you are showing here?

2023-05-25 10:06 UTC, gouravmore requested changes

2023-05-25 10:06 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +          new Date(endDate.createdDate).getTime() - new Date(startDate.createdDate).getTime());
what is the use of this? you should pass the filter from request body while calling the API

2023-05-25 11:03 UTC, poojakarma commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +          new Date(endDate.createdDate).getTime() - new Date(startDate.createdDate).getTime());
actually sir API filter not working that why i used that code to sort

2023-05-25 11:15 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +          new Date(endDate.createdDate).getTime() - new Date(startDate.createdDate).getTime());
@nidhikachhawa24 Please confirm.

2023-05-25 11:17 UTC, nidhikachhawa24 commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +          new Date(endDate.createdDate).getTime() - new Date(startDate.createdDate).getTime());
@gouravmore Yes the sorting in API is not working. I've checked myself on this and different API's also. That's why suggested to add sorting in the code itself.

2023-05-25 11:27 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +          new Date(endDate.createdDate).getTime() - new Date(startDate.createdDate).getTime());
ok

2023-05-25 11:28 UTC, gouravmore approved these changes

2023-05-29 04:27 UTC, gouravmore approved these changes

2023-05-30 05:18 UTC, merged