Task #202199 Roles of org (User Types and Count of Org)
tekdi/sunbird-admin-ui pull request #26
Opened 2023-08-02 08:12 UTC by poojakarma

Steps for Implementation:
1. Create One column for show user Roles Icon
2. Get all user Type of Organisation using API
3. After getting all User type pass each user type in API and get count from another API
4. Integrated Count in userType list 
6. Show dialog box on click of button

2023-08-03 05:01 UTC, sanjeev-scm approved these changes
The user type count API is called for each user type in the organisation as there is no support for the API

2023-08-11 04:21 UTC, sanjeev-scm approved these changes
Ready for merge

2023-08-18 04:36 UTC, sanjeev-scm approved these changes

2023-08-18 04:37 UTC, sanjeev-scm approved these changes
Can be merged

2023-08-18 08:01 UTC, manojLondhe requested changes

2023-08-18 08:01 UTC, manojLondhe commented on src/locales/en/en.json
> +  "PROFILE_ROLE":"User Role",
add screen/entity names prefix to all lang strings

2023-08-18 08:01 UTC, manojLondhe commented on src/locales/en/en.json
> +  "ROLE_INFO": "Roles Info",
add screen/entity names prefix to all lang strings

2023-08-18 08:01 UTC, manojLondhe commented on src/config/url.config.json
> +        "USER_CONTENT_TYPE_COUNT" :"action/composite/v3/search"
rename as `composite search url`

2023-08-18 08:01 UTC, manojLondhe commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +        console.log(error)
remove all console logs

2023-08-18 08:01 UTC, manojLondhe commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.ts
> +        console.log(error);
remove all console logs

2023-09-06 06:13 UTC, merged