(Task #202749) Sub organization and It's user count dashboard
tekdi/sunbird-admin-ui pull request #28
Opened 2023-08-07 12:42 UTC by poojakarma

Steps for Implementation
1. Set Link if sub-org count is greater than 0 
2. create one component to show sub-org details and it's count
3. after create component create UI to show details
4. Get all Sub-org using API
5. Show on UI sub-org details
6. After getting all sub-org id's pass in another api to get count of user
7. After getting count of user of each sub-org integrate count in exiting sub-org object
8. show user Count in table with sub-org
9. Set loader if API taking time to get response
10. set warning msg if data not found or API given error
11. set Search filter on UI to search sub-org

Video : https://drive.google.com/file/d/1nqyQZ69oc_MkH8VMk8WaW9Ne7rIwGSMW/view?usp=drive_link

2023-08-08 11:50 UTC, sanjeev-scm requested changes
Remove the sub-organization ID from the sub-organization component.
Re-introduce the .scss component for sub-organization component for future application of any styles by putting some comment and see if it resolves the sonar issue.

2023-08-09 04:36 UTC, sanjeev-scm approved these changes
Implemented the requested changes

2023-10-09 12:31 UTC, gouravmore commented on src/app/layout/app.topbar.component.html
> +    <h4><b>Admin Dashboard</b></h4>
Use language constants

2023-10-09 12:42 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sb-organization.component.html
> +                            <ng-container *ngIf="organization.subOrgCount === 0;"> {{ organization.subOrgCount }} </ng-container>
semicolon not required in if condition

2023-10-09 12:42 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sub-org-details/sub-org-details.component.html
> +                <th scope="col"></th>
Are we showing this empty?

2023-10-09 12:42 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sub-org-details/sub-org-details.component.ts
> +        this.messageService.add({ severity: 'error', summary: "Oops! Something went wrong. Please try again later" })
use language constants for the error message

2023-10-09 12:42 UTC, gouravmore commented on src/app/sb-admin/components/pages/sb-organization/sub-org-details/sub-org-details.component.ts
> +        limit: event?.rows || 10,
use constants for default value

2024-02-01 08:59 UTC, closed without merging